version: "3"

services:
  db-postgres-sipav:
    image: postgres:alpine
    container_name: db-postgres-sipav
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sipav
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data:
